import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: "400",
  style: "normal",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="h-screen">
        <Navbar />
        <main className="mt-20 mx-12">{children}</main>
      </body>
    </html>
  );
}
